In [1]:
def show_time(process, time_start, time_end):
    time_took = "\n" + str(process) + " finished in "
    if (round((time_end-time_start)/60, 1) < 1):
      time_took = time_took + str(round((time_end-time_start), 1)) + " seconds "
    elif (round((time_end-time_start)/60/60, 1) < 1):
      time_took = time_took + str(round((time_end-time_start)/60, 1)) + " minutes "
    else:
      time_took = time_took + str(round((time_end-time_start)/60/60, 1)) + " hours "
    time_took = time_took + "(wall clock).\n\n"
    return time_took
########## end of show_time function

In [2]:
import os, sys, time, torch
import pandas as pd

In [3]:
!ls

analyze_emory_data_set.ipynb     analyze_synthetic_data_set.ipynb

In [4]:
%load_ext autoreload
%autoreload 2

os.chdir("/Users/kimd999/research/projects/Vlad/code/DL-Batch-Correction")
from load_data import load_labeled_data

## synthetic data

In [5]:
synthetic_path_to_data    = '/Users/kimd999/research/projects/Vlad/data/DL-Batch-Correction-Data/data/synth_v2/synth_data.txt'
synthetic_path_to_labels  = '/Users/kimd999/research/projects/Vlad/data/DL-Batch-Correction-Data/data/synth_v2/synth_labels.txt'

train_data, test_data, metadata = load_labeled_data(synthetic_path_to_data, synthetic_path_to_labels)

print (f"len(train_data):{len(train_data)}")
print (f"len(test_data):{len(test_data)}")
print (f"type(metadata):{type(metadata)}")
print (f"metadata['n_features']:{metadata['n_features']}")
print (f"metadata['n_batches']:{metadata['n_batches']}")

len(train_data):100
len(test_data):100
type(metadata):<class 'dict'>
metadata['n_features']:995
metadata['n_batches']:10

In [6]:
df_synthetic_data = pd.read_csv(synthetic_path_to_data, delimiter="\t")
display(df_synthetic_data.head())
df_synthetic_data.describe()

,feature,Batch_01.1,Batch_01.2,Batch_01.3,Batch_01.4,Batch_01.5,Batch_01.6,Batch_01.7,Batch_01.8,Batch_01.9,...,Batch_10.11,Batch_10.12,Batch_10.13,Batch_10.14,Batch_10.15,Batch_10.16,Batch_10.17,Batch_10.18,Batch_10.19,Batch_10.20
0,prot1_pep1,0.147825,-0.733592,-0.508707,-0.331259,-0.203110,1.577075,1.237118,0.371025,-0.030774,...,1.083148,-2.014864,-0.365731,-2.149794,1.914827,0.424928,-0.764047,-0.167592,0.322721,-0.484980
1,prot2_pep1,-0.777048,-1.236613,-0.866878,3.225620,-1.337815,1.367242,1.997034,-3.424616,-0.145948,...,3.261957,-0.955791,1.636791,1.236475,-0.845689,-1.464544,-0.656972,-1.379846,1.412697,-0.006567
2,prot3_pep1,-0.414206,1.651262,0.379265,-1.584293,0.422119,-0.118108,-0.617475,2.307395,0.090561,...,-2.247701,2.389909,-0.504198,0.262283,0.605813,2.256208,-1.092828,-0.544909,1.129141,0.028066
3,prot4_pep1,2.516591,-0.413286,2.359803,1.153490,2.413396,1.940514,-1.311011,0.653347,0.154864,...,1.797863,2.039803,5.434737,1.047157,2.294662,2.555348,-1.498778,4.103612,0.798352,1.218456
4,prot5_pep1,-0.513107,-0.412307,1.450713,0.862269,0.913136,3.776373,0.283237,0.554781,0.384265,...,-0.880829,-0.622815,-0.457725,-2.477913,2.259275,0.066196,-1.310696,0.390927,1.080300,-1.680170

,Batch_01.1,Batch_01.2,Batch_01.3,Batch_01.4,Batch_01.5,Batch_01.6,Batch_01.7,Batch_01.8,Batch_01.9,Batch_01.10,...,Batch_10.11,Batch_10.12,Batch_10.13,Batch_10.14,Batch_10.15,Batch_10.16,Batch_10.17,Batch_10.18,Batch_10.19,Batch_10.20
count,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,...,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,0.045859,0.084206,-0.011263,0.037091,0.011800,0.003763,0.015815,0.007279,0.069858,-0.047365,...,0.051931,0.053826,0.070998,0.074585,0.115676,-0.031607,0.066761,0.002530,0.090385,0.035997
std,1.495110,1.358960,1.465553,1.509513,1.452810,1.386611,1.465644,1.507560,1.431570,1.510090,...,1.544212,1.578622,1.564730,1.559375,1.547925,1.529905,1.544420,1.554986,1.543503,1.590419
min,-4.222625,-3.969840,-6.047871,-4.706309,-4.535979,-4.428302,-4.873496,-5.056868,-4.825916,-4.765046,...,-5.067367,-4.321473,-4.915984,-4.410171,-5.782044,-5.546411,-4.664234,-5.279304,-5.344310,-4.173005
25%,-0.995090,-0.771696,-1.005650,-0.975466,-0.991272,-0.928396,-0.996335,-1.036263,-0.919710,-0.985898,...,-0.906007,-1.031408,-0.936564,-1.008721,-0.854232,-1.106840,-0.953234,-1.010850,-0.879132,-1.034339
50%,0.044673,0.112017,-0.038492,0.107132,0.019667,0.003274,-0.006633,0.074489,0.071266,-0.024527,...,0.068654,0.054399,0.081456,0.124864,0.108687,-0.046195,0.041803,-0.023817,0.148977,0.020948
75%,1.115538,0.991416,1.009008,1.051799,0.986821,0.895862,1.010125,1.046232,1.035216,1.019944,...,1.039278,1.127164,1.047594,1.130252,1.113921,1.049877,1.057969,1.017074,1.154074,1.039449
max,4.289988,4.971242,4.509185,4.068887,5.092378,5.324020,4.733581,4.658688,4.940873,4.254498,...,5.312874,6.503450,8.072451,6.256597,5.048667,5.750146,5.891006,5.055763,5.276703,5.226921

In [8]:
print (os.getcwd())
df_synthetic_data.to_csv('df_synthetic_data.csv', index=False)

/Users/kimd999/research/projects/Vlad/code/DL-Batch-Correction

In [10]:
#display(df_synthetic_data.min(numeric_only=True, axis=0))
df_synthetic_data_min_per_column = df_synthetic_data.min(numeric_only=True, axis=0)
display(df_synthetic_data_min_per_column.min())

#display(df_synthetic_data.max(numeric_only=True, axis=0))
df_synthetic_data_max_per_column = df_synthetic_data.max(numeric_only=True, axis=0)
display(df_synthetic_data_max_per_column.max())

-9.14572997761913

8.07245133994352

In [21]:
df_synthetic_labels = pd.read_csv(synthetic_path_to_labels, delimiter="\t")
display(df_synthetic_labels.head())
display(df_synthetic_labels.tail())
display(df_synthetic_labels.describe())
df_synthetic_labels['batch'].unique()

       sample  batch
0  Batch_01.1      0
1  Batch_01.2      0
2  Batch_01.3      0
3  Batch_01.4      0
4  Batch_01.5      0

          sample  batch
195  Batch_10.16      9
196  Batch_10.17      9
197  Batch_10.18      9
198  Batch_10.19      9
199  Batch_10.20      9

            batch
count  200.000000
mean     4.500000
std      2.879489
min      0.000000
25%      2.000000
50%      4.500000
75%      7.000000
max      9.000000

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])